#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  #amixer -q sset Master 5%+
  /home/gus/bin/audio/volume.sh up
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  #amixer -q sset Master toggle
  /home/gus/bin/audio/volume.sh mute
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  #amixer -q sset Master 5%-
  /home/gus/bin/audio/volume.sh down
# Scroll up
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  #amixer -q sset Master 5%+
  /home/gus/bin/audio/volume.sh up
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  #amixer -q sset Master 5%+
  /home/gus/bin/audio/volume.sh down
fi

muteStatus=$(pamixer --get-mute)
volumeStatus=$(pamixer --get-volume)

if [[ "${muteStatus}" == "false" ]]; then
  echo "${volumeStatus}%"
  echo "${volumeStatus}%"
  echo ""
else
  echo "muted"
  echo "muted"
  echo ""
fi
