#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  /home/gus/bin/audio/devices/speakers.sh
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  /home/gus/bin/audio/devices/internal-speakers.sh
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  /home/gus/bin/audio/devices/headset.sh
fi

DEVICE=$(pacmd stat | grep 'Default sink name')
if [[ "$DEVICE" =~ "Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio" ]]; then
    statusLine="Speakers"
elif [[ "$DEVICE" =~ "Sennheiser_Sennheiser_3D_G4ME1" ]]; then
    statusLine="Headset"
elif [[ "$DEVICE" =~ "pci-0000_00_1f.3" ]]; then
    statusLine="Internal"
fi

echo "${statusLine}"
echo "${statusLine}"
echo ""
