#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  # thunderbolt dock
  /home/gus/bin/audio/devices/speakers.sh
  # USB soundcard
  #/home/gus/bin/audio/devices/speakers-usb.sh
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  /home/gus/bin/audio/devices/internal-speakers.sh
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  #/home/gus/bin/audio/devices/headset.sh
  /home/gus/bin/audio/devices/headphone-amp.sh
# Scroll up
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  /home/gus/bin/audio/volume.sh up
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  /home/gus/bin/audio/volume.sh down
# Back thumb button
elif [[ "${BLOCK_BUTTON}" -eq 8 ]]; then
  /home/gus/bin/audio/volume.sh mute
# Front thumb button
elif [[ "${BLOCK_BUTTON}" -eq 9 ]]; then
  /home/gus/bin/audio/devices/bluetooth.sh
fi

DEVICE=$(pacmd stat | grep 'Default sink name')
if [[ "$DEVICE" =~ "C-Media_USB_Headphone" ]]; then
    statusLine="Speakers (USB)"
elif [[ "$DEVICE" =~ "Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio" ]]; then
    statusLine="Speakers (Dock)"
elif [[ "$DEVICE" =~ "Sennheiser_Sennheiser_3D_G4ME1" ]]; then
    statusLine="Headset"
elif [[ "$DEVICE" =~ "Schiit_Audio_I_m_Fulla_Schiit" ]]; then
    statusLine="Schiit Fulla"
elif [[ "$DEVICE" =~ "bluez_sink.11_11_22_03_CC_C1.a2dp_sink" ]]; then
    statusLine="QC25 Bluetooth"
elif [[ "$DEVICE" =~ "bluez_sink.88_C6_26_91_8B_DF.a2dp_sink" ]]; then
    statusLine="UE BOOM 2"
elif [[ "$DEVICE" =~ "pci-0000_00_1f.3" ]]; then
    statusLine="Internal"
fi

muteStatus=$(pamixer --get-mute)
volumeStatus=$(pamixer --get-volume)

if [[ ${muteStatus} == "false" ]]; then
    echo "${statusLine}: ${volumeStatus}%"
    echo "${statusLine}: ${volumeStatus}%"
else
    echo "${statusLine}: muted"
    echo "${statusLine}: muted"
fi
echo ""

