#!/bin/bash
BLOCK_SIGNAL=2
PANEL_ONLY="eDP1 "

if [ -f /tmp/.display-active ]; then
    displayActive=$(cat /tmp/.display-active)
    if [[ "${displayActive}" != "Panel" ]]; then
        exit 0
    fi
else
    xrandrOut=$(xrandr)
    panelName="eDP1"
    panelRANDR="${panelName} "
    activeDisplays=$(echo "${xrandrOut}" | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | tr -s '\n' ' ')
    if [[ "${activeDisplays}" != "${panelRANDR}" ]]; then
        exit 0
    fi
fi

# One of the following: xrandr, xbacklight, kernel
METHOD="xbacklight"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xbacklight -inc 5
  pkill -RTMIN+${BLOCK_SIGNAL} i3blocks
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  xbacklight -dec 5
  pkill -RTMIN+${BLOCK_SIGNAL} i3blocks
# Scroll up
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  xbacklight -inc 5
  pkill -RTMIN+${BLOCK_SIGNAL} i3blocks
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  xbacklight -dec 5
  pkill -RTMIN+${BLOCK_SIGNAL} i3blocks
fi

URGENT_VALUE=10

if [[ "${METHOD}" = "xrandr" ]]; then
  device="${BLOCK_INSTANCE:-primary}"
  xrandrOutput=$(xrandr --verbose)

  if [[ "${device}" = "primary" ]]; then
    device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
  fi

  curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
elif [[ "${METHOD}" = "kernel" ]]; then
  device="${BLOCK_INSTANCE:-intel_backlight}"
  maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
  curBrightness=$(cat /sys/class/backlight/${device}/brightness)
elif [[ "${METHOD}" = "xbacklight" ]]; then
  curBrightness=$(xbacklight -get)
fi

if [[ "${curBrightness}" -le 0 ]]; then
  exit
fi

if [[ "${METHOD}" = "xrandr" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "kernel" ]]; then
  percent=$(echo "scale=0;${curBrightness} / ${maxBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "xbacklight" ]]; then
  percent=$(echo "scale=0;${curBrightness}" | bc -l)
fi

percent=${percent%.*}

if [[ "${percent}" -le 0 ]]; then
  exit
fi

echo "${percent}%"
echo "${percent}%"
echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
