#!/bin/bash

FORMAT="${BLOCK_INSTANCE:-%H:%M}"
#DATETIME=$(date "+${FORMAT}")
#DATETIME=$(echo "`date +'%a %d %b'` <b>`date +'%T'`</b> ")
DATETIME=$(echo "`date +'%a %d %b'` <b>`date +'%H:%M'`</b> ")

echo "${DATETIME}"
echo "${DATETIME}"
echo ""
