#!/bin/bash

xrandrOut=$(xrandr)

dpName=$(echo "${xrandrOut}" | grep -i 'DP-1' | awk '{print $1}')
#vgaName=$(echo "${xrandrOut}" | grep -i 'VGA' | awk '{print $1}')
edpName=$(echo "${xrandrOut}" | grep -i 'eDP-1' | awk '{print $1}')

activeDisplays=$(echo "${xrandrOut}" | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | tr -s '\n' ' ')
displayFile='/tmp/.displays'

if [[ -f "${displayFile}" ]]; then
    oldDisplays=$(cat "${displayFile}")
else
    oldDisplays=""
fi

if [[ "${oldDisplays}" != "${activeDisplays}" ]]; then
    change="yes"
else
    change="no"
fi

# External, HDMI + VGA
#if [[ "$activeDisplays" =~ "${dpName}" && "$activeDisplays" =~ "${vgaName}" ]]; then
#  if [[ "${change}" = "yes" ]]; then
#    $(xrandr --output "${edpName}" --off)
#    $(xrandr --output "${vgaName}" --auto)
#    $(xrandr --output "${dpName}" --primary --auto)
#  fi
#  echo "VGA1 & HDMI"
#  echo "VGA1 & HDMI"
#  echo ""
# External DP
if [[ "$activeDisplays" =~ "${dpName}" ]]; then
  if [[ "${change}" = "yes" ]]; then
    $(xrandr --output "${edpName}" --off)
    #$(xrandr --output "${vgaName}" --off)
    $(xrandr --output "${dpName}" --primary --auto)
  fi
  echo "DP"
  echo "DP"
  echo ""
# Internal only
elif [[ "$activeDisplays" =~ "${edpName}" ]]; then
  if [[ "${change}" = "yes" ]]; then
    $(xrandr --output "${edpName}" --primary --auto)
    #$(xrandr --output "${vgaName}" --off)
    $(xrandr --output "${dpName}" --off)
  fi
  echo "eDP"
  echo "eDP"
  echo ""
fi

if [[ "${change}" = "yes" ]]; then
  echo "${activeDisplays}" > "${displayFile}"
fi
