#!/bin/bash -x

xrandrOut=$(xrandr)

dpName=$(echo "${xrandrOut}" | grep -i 'DP1' | awk '{print $1}')
panelName=$(echo "${xrandrOut}" | grep -i 'eDP1' | awk '{print $1}')

activeDisplays=$(echo "${xrandrOut}" | grep " connected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/" | tr -s '\n' ' ')
displayFile='/tmp/.displays'

if [[ -f "${displayFile}" ]]; then
    oldDisplays=$(cat "${displayFile}")
else
    oldDisplays=""
fi

if [[ "${oldDisplays}" != "${activeDisplays}" ]]; then
    change="yes"
else
    change="no"
fi

# left click forces a display change
if [[ "${BLOCK_BUTTON}" -eq "1" ]]; then
    change="yes"
fi

# External, HDMI + VGA
#if [[ "$activeDisplays" =~ "${dpName}" && "$activeDisplays" =~ "${vgaName}" ]]; then
#  if [[ "${change}" = "yes" ]]; then
#    $(xrandr --output "${panelName}" --off)
#    $(xrandr --output "${vgaName}" --auto)
#    $(xrandr --output "${dpName}" --primary --auto)
#  fi
#  echo "VGA1 & HDMI"
#  echo "VGA1 & HDMI"
#  echo ""

# External DP
if [[ "$activeDisplays" =~ "${dpName}" ]]; then
  if [[ "${change}" = "yes" ]]; then
    $(xrandr --output "${panelName}" --off --output "${dpName}" --primary --auto)
  fi
  echo "External"
  echo "External"
  echo ""
# Internal only
elif [[ "$activeDisplays" =~ "${panelName}" ]]; then
  if [[ "${change}" = "yes" ]]; then
    $(xrandr --output "${panelName}" --primary --auto --output "${dpName}" --off)
  fi
  echo "Panel"
  echo "Panel"
  echo ""
fi

if [[ "${change}" = "yes" ]]; then
  echo "${activeDisplays}" > "${displayFile}"
fi
