#!/bin/bash
CONNECTION_NAME="vpn.home.webvictim.net" 

# left click to connect
if [[ "${BLOCK_BUTTON}" == "1" ]]; then
    nmcli con up id ${CONNECTION_NAME} 2>&1 >/dev/null
# right click to disconnect
elif [[ "${BLOCK_BUTTON}" == "3" ]]; then
    nmcli con down id ${CONNECTION_NAME} 2>&1 >/dev/null
fi

VPN_STATUS=$(nmcli con show id ${CONNECTION_NAME} | grep VPN-STATE | grep -q "VPN connected")
if [ $? -eq 0 ]; then
    VPN_STATUS="VPN on"
else
    VPN_STATUS="VPN off"
fi

echo "${VPN_STATUS}"
echo "${VPN_STATUS}"
echo ""
