#!/bin/bash
#DELAY=0.05
DELAY=0
#PLAYER_LIST="DeaDBeeF,spotify,rhythmbox"
# automatically picks the most recently-used player
PLAYER_LIST="playerctld"
CHROME_ID=$(playerctl -l | grep chrome)

if [[ "${CHROME_ID}" != "" ]]; then
    PLAYERCTL="playerctl --player=${PLAYER_LIST} --ignore-player=${CHROME_ID}"
else
    PLAYERCTL="playerctl --player=${PLAYER_LIST}"
fi

print_status() {
    pauseStatus=$(${PLAYERCTL} status 2>&1 | egrep -v "^$" | head -n1)
    if [[ "${pauseStatus}" == "No players found" || "${pauseStatus}" == "No player could handle this command" || "${pauseStatus}" == "" ]]; then
        echo "Cannot find player"
        echo "Cannot find player"
        echo ""
        exit 1
    fi
    if [ $? -gt 0 ]; then
        exit 1
    fi
    if [[ "${pauseStatus}" == "Stopped" ]]; then
        exit 0
    fi
    artist=$(${PLAYERCTL} metadata artist)
    title=$(${PLAYERCTL} metadata title)
    playerMetadata="${artist} | ${title}"
    pauseString=""
    if [[ "${pauseStatus}" == "Paused" ]]; then
        pauseString=" "
    fi

    echo "${playerMetadata}${pauseString}"
    echo "${playerMetadata}${pauseString}"
    echo ""    
}

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    #qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
    ${PLAYERCTL} next
    sleep ${DELAY}
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    #qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
    ${PLAYERCTL} play-pause
    sleep ${DELAY}
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    #qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
    ${PLAYERCTL} previous
    sleep ${DELAY}
fi

print_status
