#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
fi

spotifyStatus=$(~/bin/spotify.py)

echo "${spotifyStatus}"
echo "${spotifyStatus}"
echo ""
