#!/bin/bash

TEMP_DEVICE="${BLOCK_INSTANCE:-Core}"
TEMP=$(sensors | grep -A2 acpitz | grep ${TEMP_DEVICE} | awk '{printf ("%.0f\n", $2)}')

if [[ "${TEMP}" == "" ]]; then
    echo "Error"
    echo "Error"
    echo ""
    exit 1
fi

echo "${TEMP}°C"
echo "${TEMP}°C"
echo ""

